
using System.Collections.Generic;

namespace RASCAL.Localization {
    public class English : Locale {

        new public static string GetTooltip(string memberName) {
            _tooltips.TryGetValue(memberName, out var tip);
            return tip;
        }

        new public static string GetName(string memberName) {
            _names.TryGetValue(memberName, out var name);
            return name;
        }

        new public static string GetMsg(string memberName) {
            _messages.TryGetValue(memberName, out var msg);
            return msg;
        }

        internal new static string isoCodeStatic => "en";
        internal override string isoCode => isoCodeStatic;
        internal override Dictionary<string, string> names => _names;
        internal override Dictionary<string, string> tooltips => _tooltips;
        internal override Dictionary<string, string> messages => _messages;


        static readonly Dictionary<string, string> _names = new Dictionary<string, string> {
            {"clear", "Clear"},
            {"generation", "Generation"},
            {"updating", "Updating"},
            {"materialAssociationsAndExclusions", "Material Associations & Exclusions"},
            {"materialAssociationList", "Material Associations"},
            {"addExclusions", "Add Exclusions"},
            {"clearAllMeshColliders", "All Mesh Colliders"},
            {"generateOnStart", "Generate On Start"},
            {"immediateStartupCollision", "Immediate Startup Collision"},
            {"onlyUniqueTriangles", "Only Unique Triangles"},
            {"splitCollisionMeshesByMaterial", "Split Collision Meshes By Material"},
            {"zeroBoneMeshAlternateTransform", "Zero Bone Mesh Alternate Transform"},
            {"convexMeshColliders", "Convex Mesh Colliders"},
            {"boneWeightThreshold", "Bone Weight Threshold"},
            {"maxColliderTriangles", "Max Collider Triangles"},
            {"physicsMaterial", "Physics Material"},
            {"enableUpdatingOnStart", "Enable Updating On Start"},
            {"useThreadedColMeshBaking", "Use Threaded Col Mesh Baking"},
            {"idleCpuBudget", "Idle CPU Budget"},
            {"activeCpuBudget", "Active CPU Budget"},
            {"meshUpdateThreshold", "Mesh Update Threshold"}
        };

        static readonly Dictionary<string, string> _tooltips = new Dictionary<string, string> {
            {"clear", "Destroy all mesh colliders and data generated by this script. " +
            "This isn't needed anymore, but I'll leave it here just in case."},
            {"clearAllMeshColliders", "Clears ALL mesh colliders under the component when calling the clear function, not just colliders currently associated with this component. Be careful with this."},
            {"materialAssociationList", "Use this list to associate materials in the skinned mesh(es) with physics materials that will be added to the mesh colliders. If your mesh has multiple materials make sure to check the option to split the collision meshes by material."},
            {"addExclusions", "Drag either a skinned mesh, bone-transform, or material into the slots below to add them to the exclusion list. This will make it so collision meshes will not be generated for the given meshes, bone-transforms, and materials."},
            {"generateOnStart", "This will process and generate all necessary data to create the bone-meshes used in collision and also generate some initial collision shapes when the game starts."},
            {"immediateStartupCollision", "This generates collision on startup immediately, rather than using the asynchronous method which could take second or two to fully generate. This obviously comes at the cost of longer initial game load times. If you don't need the collision immediately within a few seconds of the game loading, it is recommended not to enable this."},
            {"onlyUniqueTriangles", "When enabled, only unique triangles will be used between all the bone-meshes. This prevents mesh overlapping but because of how triangles are chosen without any care for which bone the triangle is more significant to, this can lead to messy bone-meshes that may impact results of certain collisions. It's bit faster and uses less memory, this option should probably be on unless you notice some otherwise bad collision meshes being generated as a result of it."},
            {"splitCollisionMeshesByMaterial", "Splits each collision mesh up by material. For example if your skinned mesh has 2 materials it will create 1 collider for all triangles with the first material, and another for the second material. This is useful and required mostly for applying different physics materials to the colliders based on material or excluding mesh parts based on material. To do that, use the material association list and the exclusion list."},
            {"zeroBoneMeshAlternateTransform", "You almost certainly don't need this. But it's included just in case. It basically makes it so meshes with no bones and only blendshapes get transformed differently. But it should be fine by default, this should be a last resort troubleshooting step."},
            {"convexMeshColliders", "Enable the convex setting of the mesh colliders. This option obviously leads to inaccuracies in the overall mesh and you may need to lower the max polygons per mesh to avoid errors, but convex meshes should allow for non-kinematic rigid bodies to be used if that's something that you need."},
            {"boneWeightThreshold", "When generating colliders, the bone weight for the vertex must be above this for the vertex to be added to the collider."},
            {"maxColliderTriangles", "The maximum number of triangles/polygons to allow in each collision shape. The mesh will be split up into multiple mesh colliders if it contains more than this amount. Splitting large meshes up can help with asynchronous collision generate frame rate stability as large meshes may cause hitching when updating mesh colliders. Splitting the mesh up however can very slightly make it take longer to update all collision shapes, this is probably negligible though."},
            {"physicsMaterial", "Material to apply to the mesh colliders. If you need more granular control for materials on what bones youll need to add a RASCALProperties component to the bone transform or skinned-mesh transform. The priority goes from highest to lowest: Material-Association-List -> Bone-Transform -> SkinnedMesh-Transform -> PhysicsMaterial-Variable"},
            {"enableUpdatingOnStart", "This will enable continuous asynchronous updating of collision shapes when the game starts. You may find that the initial collision shapes work well enough for you and you dont even need to update them which would save on performance for sure, but if the mesh deforms due to its bones being moved the shapes wont match and could cause some pretty big inaccuracies. Alternatively, if you know your mesh will only need to be updated at certain points, you can call either immediate or asynchronous reconstruction of the collision shapes manually via the provided functions in the script."},
            {"useThreadedColMeshBaking", "Uses a new feature in Unity to bake collision mesh data manually on a separate thread. The baking step is the most costly step of updating meshes, so enabling this leaves the main thread free to do more of the stuff that requires it. However this comes at a moderate tradeoff in that each individual collider will take longer to update due to the overhead threading. On a modern computer this is still probably faster overall just because multiple different colliders can be processed at a time on separate threads."},
            {"idleCpuBudget", "Amount of time in milliseconds the asynchronous generation should be allowed to run per frame while idling. It is idling when the mesh isnt changing enough to warrant rebuilding the collision shapes. (this setting doesn't affect immediate updating)"},
            {"activeCpuBudget", "Amount of time in milliseconds the asynchronous generation should be allowed to run per frame while active. It is active when any of the collision shapes are actively being rebuilt. This allows more time to rebuild collision shapes which means they will update faster at the cost of performance. (this setting doesn't affect immediate updating)"},
            {"meshUpdateThreshold", "An amount by which the bone mesh needs to change in order for its collision to be rebuilt. The purpose of this is to allow for slight changes in the mesh before comepletely rebuilding, which slightly improves performance at the cost of accuracy. The value for this should likely be quite small but you should play around with it to see what works best for you."}
        };

        static readonly Dictionary<string, string> _messages = new Dictionary<string, string> {
            {"changeVariableUndo", "RASCAL Change Variable"},
            {"addMaterialAssociationUndo", "Add RASCAL Material Association"},
            {"removeMaterialAssociationUndo", "Remove RASCAL Material Association"},
            {"setMaterialUndo", "RASCAL MA Set Material"},
            {"setPhysMatUndo", "RASCAL MA Set PhysMat"},
            {"addExcludedSkinnedMeshUndo", "RASCAL Add Excluded SkinnedMesh"},
            {"addExcludedMaterialUndo", "RASCAL Add Excluded Material"},
            {"addExcludedBoneUndo", "RASCAL Add Excluded Bone"},
            {"removeExcludedSkinnedMeshUndo", "Remove RASCAL Excluded SkinnedMesh"},
            {"removeExcludedBoneUndo", "Remove RASCAL Excluded Bone"},
            {"removeExcludedMaterialUndo", "Remove RASCAL Excluded Material"},

            //--------------------------------------------------------------------------------
			//MISC---------------------------------------------------------------
			//--------------------------------------------------------------------------------
			{ "languageSelectorTitle", "RASCAL Language Selector" },
            { "selectLanguagePrompt", "Please select a language:" },
            { "languageLabel", "Language:" },
            { "confirmSelectionButton", "Confirm Selection" },
        };
    }
}